### ISSUE TITLE
Configuration file  design to mount the servers 

### ISSUE THREAD

**Issue by LCailliot** [LCailliot/easymount#2]
# Overview

Design a configuration file to mount VMs.

Mandatory configurations :

* [ ] os: String
* [ ] servers: List
    * [ ] hostname: String

Optional configuration
* [ ] disk : int, disk size in GB, override default `20`
* [ ] memory: int, VRAM memory in MB, override default `4096`
* [ ] vcpu: int, number of cpu, override default `1` 
* [ ] servers: List
    * [ ] OS : string, global override
    * [ ] IP : string, global override
    * [ ] disk : int, global override
    * [ ] memory: int, global override
    * [ ] vcpu: int, global override

## Example

example 1 :

```yaml
platform:
  os: centos8
  servers:
    - hostname: vm1
    - hostname: vm2
```

example 2 :

```yaml
platform:
  os: centos8
  disk: 30
  memory: 2048
  vcpu: 2
  servers:
    - hostname: vm1
    - hostname: vm2
      disk: 25
      memory: 3
      vcpu: 1
```
